proxy-providers:
  QQ:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸŸ¢ ç›´è¿
    url: é“¾æ¥
global-ua: clash.meta
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb

external-controller: 0.0.0.0:9090
secret: '12345'
external-ui: "/usr/share/openclash/ui"
external-ui-url: https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip

find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - "+.push.apple.com"
    - "+.apple.com"
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - geosite:private
    - geosite:cn
  default-nameserver:
    - 219.147.1.66
    - 223.5.5.5
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    rule-set:private_domain,cn_domain:
      - 219.147.1.66
      - 223.5.5.5
    rule-set:geolocation-!cn:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
  
proxies:
- name: "ğŸŸ¢ ç›´è¿"
  type: direct
  udp: true
 
# é”šç‚¹
pr: &pr {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ¸ æ‰‹åŠ¨é€‰æ‹©, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸŸ¢ ç›´è¿, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨]}
# ç­–ç•¥ç»„
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡­ğŸ‡° é¦™æ¸¯å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬å€ç‡, ğŸ‡ºğŸ‡² ç¾å›½å€ç‡, â“ å…¶ä»–èŠ‚ç‚¹, ğŸ¸ æ‰‹åŠ¨é€‰æ‹©, ğŸŸ¢ ç›´è¿]}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸ¸ æ‰‹åŠ¨é€‰æ‹©, type: select, include-all: true, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(é¦™æ¸¯|æ¸¯|ğŸ‡­ğŸ‡°|(?i)hk|(?i)hong))"}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯å€ç‡, type: select, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(é¦™æ¸¯|æ¸¯|ğŸ‡­ğŸ‡°|(?i)hk|(?i)hong)(?=.*å€ç‡))"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å°æ¹¾|æ¹¾|ğŸ‡¹ğŸ‡¼|Taiwan|TW))"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥æœ¬|æ—¥|ä¸œäº¬|ğŸ‡¯ğŸ‡µ|(?i)jp|(?i)japan))" }
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬å€ç‡, type: select, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ—¥æœ¬|æ—¥|ä¸œäº¬|ğŸ‡¯ğŸ‡µ|(?i)jp|(?i)japan)(?=.*å€ç‡))" }
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(éŸ©å›½|éŸ©|ğŸ‡°ğŸ‡·|(?i)kr|(?i)korea))"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾å›½|ç¾|å‡¤å‡°åŸ|ğŸ‡ºğŸ‡²|(?i)us|(?i)states|(?i)america))"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½å€ç‡, type: select, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾å›½|ç¾|å‡¤å‡°åŸ|ğŸ‡ºğŸ‡²|(?i)us|(?i)states|(?i)america)(?=.*å€ç‡))"}
  - {name: â“ å…¶ä»–èŠ‚ç‚¹, type: select, include-all: true, tolerance: 20, interval: 300, filter: "^(?!.*(é¦™æ¸¯|æ¸¯|ğŸ‡­ğŸ‡°|hk|hong|å°æ¹¾|æ¹¾|ğŸ‡¹ğŸ‡¼|taiwan|tw|æ—¥æœ¬|æ—¥|ä¸œäº¬|ğŸ‡¯ğŸ‡µ|jp|japan|éŸ©å›½|éŸ©|ğŸ‡°ğŸ‡·|kr|korea|ç¾å›½|ç¾|å‡¤å‡°åŸ|ğŸ‡ºğŸ‡²|us|states|america|å‰©ä½™|å¥—é¤|å®˜ç½‘|å»ºè®®|ç›´è¿)).*"}
  - {name: ğŸ¤– ChatGPT, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨]}
  - {name: ğŸµ TikTok, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬å€ç‡, ğŸ‡­ğŸ‡° é¦™æ¸¯å€ç‡]}
  - {name: â–¶ï¸ YouTube, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬å€ç‡, ğŸ‡­ğŸ‡° é¦™æ¸¯å€ç‡]}
  - {name: ğŸ…¾ Instagram, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬å€ç‡, ğŸ‡­ğŸ‡° é¦™æ¸¯å€ç‡]}
  - {name: ğŸªŸ Microsoft, type: select, proxies: [ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸŸ¢ ç›´è¿]}
  - {name: ğŸ Apple, type: select, proxies: [ğŸŸ¢ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ  æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸŸ¢ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]} 
 

rules:
  - RULE-SET,private_domain,ğŸŸ¢ ç›´è¿
  - RULE-SET,my-tw-proxy,ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨
  - RULE-SET,my-direct,ğŸŸ¢ ç›´è¿
  - RULE-SET,my-proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,adblock,REJECT
  - RULE-SET,openai_domain,ğŸ¤– ChatGPT
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,youtube_domain,â–¶ï¸ YouTube
  - RULE-SET,google_domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,github_domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,telegram_domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,instagram_domain,ğŸ…¾ Instagram
  - RULE-SET,apple_domain,ğŸ Apple    
  - RULE-SET,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,cn_domain,ğŸŸ¢ ç›´è¿
  - RULE-SET,google_ip,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,no-resolve
  - RULE-SET,telegram_ip,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,no-resolve
  - RULE-SET,cn_ip,ğŸŸ¢ ç›´è¿
  - MATCH,ğŸ  æ¼ç½‘ä¹‹é±¼

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qcy: &qcy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  my-direct: {!!merge <<: *class, url: "https://raw.githubusercontent.com/AlbertMusk/Rules/refs/heads/main/clash/Direct.list" }
  my-proxy: {!!merge <<: *class, url: "https://raw.githubusercontent.com/AlbertMusk/Rules/refs/heads/main/clash/ProxyLite.list" }
  my-tw-proxy: {!!merge <<: *class, url: "https://raw.githubusercontent.com/AlbertMusk/Rules/refs/heads/main/clash/TWProxyList" }
  adblock: {!!merge <<: *class, url: "https://raw.githubusercontent.com/REIJI007/AdBlock_Rule_For_Clash/main/adblock_reject.mrs" }
  openai_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs" }  
  youtube_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  telegram_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  microsoft_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  tiktok_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  gfw_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}  
  cn_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  instagram_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/instagram.mrs"}
  github_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/github.mrs"}
